# Generated by Django 4.2.7 on 2025-09-09 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_backup', models.DateTimeField(auto_now_add=True, verbose_name='Data do Backup')),
                ('arquivo_backup', models.FileField(upload_to='backups/', verbose_name='Arquivo de Backup')),
                ('tamanho_arquivo', models.BigIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Backup Realizado com Sucesso')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Backup de Dados',
                'verbose_name_plural': 'Backups de Dados',
                'ordering': ['-data_backup'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('peso', models.IntegerField(default=1, verbose_name='Peso')),
                ('questoes_prova', models.IntegerField(default=0, verbose_name='Questões na Prova')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='pdfs/', verbose_name='Arquivo PDF')),
                ('conteudo_extraido', models.TextField(verbose_name='Conteúdo Extraído')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Documento PDF',
                'verbose_name_plural': 'Documentos PDF',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('certo_errado', 'Certo/Errado')], default='multipla_escolha', max_length=20, verbose_name='Tipo')),
                ('alternativas', models.JSONField(verbose_name='Alternativas')),
                ('resposta_correta', models.CharField(max_length=1, verbose_name='Resposta Correta')),
                ('explicacao', models.TextField(verbose_name='Explicação')),
                ('justificativa_alternativas', models.JSONField(default=dict, verbose_name='Justificativa das Alternativas')),
                ('referencia_pdf', models.TextField(blank=True, null=True, verbose_name='Referência no PDF')),
                ('nivel_dificuldade', models.CharField(choices=[('fixacao', 'Fixação - Conteúdo do PDF'), ('medio', 'Médio - Aplicação Lógica'), ('dificil', 'Difícil - Lógica + Raciocínio Aplicado'), ('nivel_banca', 'Nível da Banca - Questão Real')], max_length=20, verbose_name='Nível de Dificuldade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('total_tentativas', models.IntegerField(default=0, verbose_name='Total de Tentativas')),
                ('total_acertos', models.IntegerField(default=0, verbose_name='Total de Acertos')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('pdf_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pdfdocument', verbose_name='PDF de Origem')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Tópico')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['disciplina', 'nome'],
                'unique_together': {('disciplina', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='TentativaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escolhida', models.CharField(max_length=1, verbose_name='Resposta Escolhida')),
                ('acertou', models.BooleanField(verbose_name='Acertou')),
                ('tempo_resposta', models.IntegerField(default=0, verbose_name='Tempo de Resposta (segundos)')),
                ('data_tentativa', models.DateTimeField(auto_now_add=True, verbose_name='Data da Tentativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questao', verbose_name='Questão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Questão',
                'verbose_name_plural': 'Tentativas de Questões',
                'ordering': ['-data_tentativa'],
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topico', verbose_name='Tópico'),
        ),
        migrations.CreateModel(
            name='EstatisticaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questoes_tentadas', models.IntegerField(default=0, verbose_name='Total de Questões Tentadas')),
                ('total_acertos', models.IntegerField(default=0, verbose_name='Total de Acertos')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de Erros')),
                ('acertos_fixacao', models.IntegerField(default=0, verbose_name='Acertos - Fixação')),
                ('acertos_medio', models.IntegerField(default=0, verbose_name='Acertos - Médio')),
                ('acertos_dificil', models.IntegerField(default=0, verbose_name='Acertos - Difícil')),
                ('acertos_nivel_banca', models.IntegerField(default=0, verbose_name='Acertos - Nível da Banca')),
                ('tentativas_fixacao', models.IntegerField(default=0, verbose_name='Tentativas - Fixação')),
                ('tentativas_medio', models.IntegerField(default=0, verbose_name='Tentativas - Médio')),
                ('tentativas_dificil', models.IntegerField(default=0, verbose_name='Tentativas - Difícil')),
                ('tentativas_nivel_banca', models.IntegerField(default=0, verbose_name='Tentativas - Nível da Banca')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estatística do Usuário',
                'verbose_name_plural': 'Estatísticas dos Usuários',
                'ordering': ['disciplina'],
                'unique_together': {('usuario', 'disciplina')},
            },
        ),
    ]
