# Generated by Django 4.2.7 on 2025-09-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='materia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Matéria/Assunto'),
        ),
    ]
