# Generated by Django 4.2.7 on 2025-09-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pdfdocument_disciplina_pdfdocument_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='hash_arquivo',
            field=models.CharField(blank=True, help_text='SHA-256 do arquivo para detecção de duplicatas', max_length=64, null=True, unique=True, verbose_name='Hash do Arquivo'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='tamanho_arquivo',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo (bytes)'),
        ),
    ]
