# Generated by Django 4.2.7 on 2025-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pdfdocument_hash_arquivo_pdfdocument_tamanho_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='hash_conteudo',
            field=models.CharField(blank=True, help_text='Hash SHA-256 do enunciado para evitar duplicatas', max_length=64, null=True, unique=True, verbose_name='Hash do Conteúdo'),
        ),
    ]
