# Generated by Django 4.2.7 on 2025-09-10 12:40

from django.db import migrations
from django.db.models import F


def populate_materias(apps, schema_editor):
    """Popula matérias baseadas nos PDFs existentes"""
    PDFDocument = apps.get_model('core', 'PDFDocument')
    Materia = apps.get_model('core', 'Materia')
    Disciplina = apps.get_model('core', 'Disciplina')
    
    # Para cada PDFDocument com matéria como string
    for pdf in PDFDocument.objects.filter(materia__isnull=False, disciplina__isnull=False):
        if pdf.materia and pdf.disciplina:
            # Cria ou busca a matéria
            materia_obj, created = Materia.objects.get_or_create(
                disciplina=pdf.disciplina,
                nome=pdf.materia,
                defaults={'descricao': f'Matéria criada automaticamente para {pdf.disciplina.nome}'}
            )
            print(f"Matéria {'criada' if created else 'encontrada'}: {materia_obj.nome} para {pdf.disciplina.nome}")


def reverse_populate_materias(apps, schema_editor):
    """Reverte a população de matérias"""
    # Não precisa fazer nada para reverter
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_materia_model_only'),
    ]

    operations = [
        migrations.RunPython(populate_materias, reverse_populate_materias),
    ]
