# Generated by Django 4.2.7 on 2025-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvaAntiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título da Prova')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('banca', models.CharField(choices=[('idecan', 'IDECAN'), ('cespe', 'CESPE'), ('fcc', 'FCC'), ('fcc', 'FGV'), ('outro', 'Outro')], default='idecan', max_length=50, verbose_name='Banca')),
                ('tipo', models.CharField(choices=[('prova_oficial', 'Prova Oficial'), ('simulado', 'Simulado'), ('edital', 'Edital'), ('outro', 'Outro')], default='prova_oficial', max_length=20, verbose_name='Tipo')),
                ('arquivo_pdf', models.FileField(upload_to='provas_antigas/', verbose_name='Arquivo PDF')),
                ('conteudo_texto', models.TextField(blank=True, null=True, verbose_name='Conteúdo Extraído')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('disciplinas_identificadas', models.JSONField(blank=True, default=dict, verbose_name='Disciplinas Identificadas')),
                ('padroes_recorrencia', models.JSONField(blank=True, default=dict, verbose_name='Padrões de Recorrência')),
                ('distribuicao_questoes', models.JSONField(blank=True, default=dict, verbose_name='Distribuição de Questões')),
                ('total_questoes', models.IntegerField(default=0, verbose_name='Total de Questões')),
                ('processado', models.BooleanField(default=False, verbose_name='Processado')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Prova Antiga',
                'verbose_name_plural': 'Provas Antigas',
                'ordering': ['-ano', '-data_upload'],
            },
        ),
    ]
