# Generated by Django 4.2.7 on 2025-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_provaantiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='provaantiga',
            name='quantidade_questoes_por_disciplina',
            field=models.JSONField(blank=True, default=dict, verbose_name='Quantidade de Questões por Disciplina'),
        ),
    ]
