# Generated by Django 4.2.7 on 2025-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_provaantiga_quantidade_questoes_por_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='provaantiga',
            name='configuracao_questoes',
            field=models.TextField(blank=True, null=True, verbose_name='Configuração de Questões (Ex: Língua Portuguesa: 5, Matemática: 10)'),
        ),
    ]
