# Generated by Django 4.2.7 on 2025-09-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_provaantiga_configuracao_questoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provaantiga',
            name='configuracao_questoes',
        ),
        migrations.AddField(
            model_name='provaantiga',
            name='quantidade_total_questoes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade Total de Questões (1-80)'),
        ),
    ]
