# Generated by Django 4.2.7 on 2025-09-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_provaantiga_configuracao_questoes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupDados',
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='materia',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='tentativaquestao',
            name='questao',
        ),
        migrations.RemoveField(
            model_name='tentativaquestao',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='topico',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topico',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='topico',
        ),
        migrations.DeleteModel(
            name='EstatisticaUsuario',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='TentativaQuestao',
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
