# Generated by Django 4.2.7 on 2025-09-11 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_delete_backupdados_alter_materia_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escolhida', models.CharField(max_length=1, verbose_name='Resposta Escolhida')),
                ('acertou', models.BooleanField(verbose_name='Acertou')),
                ('data_tentativa', models.DateTimeField(auto_now_add=True, verbose_name='Data da Tentativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questao', verbose_name='Questão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Questão',
                'verbose_name_plural': 'Tentativas de Questões',
                'ordering': ['-data_tentativa'],
                'unique_together': {('usuario', 'questao')},
            },
        ),
    ]
