# Generated by Django 4.2.7 on 2025-09-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tentativaquestao'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='afirmacoes',
            field=models.JSONField(blank=True, help_text="Lista de afirmações para questões do tipo 'Afirmações'", null=True, verbose_name='Afirmações'),
        ),
        migrations.AddField(
            model_name='questao',
            name='instrucao_texto',
            field=models.CharField(blank=True, help_text='Texto personalizado da instrução', max_length=200, null=True, verbose_name='Texto da Instrução'),
        ),
        migrations.AddField(
            model_name='questao',
            name='instrucao_tipo',
            field=models.CharField(blank=True, choices=[('correto', 'Está CORRETO o que se afirma'), ('incorreto', 'Está INCORRETO o que se afirma'), ('corretos', 'Estão CORRETOS os itens'), ('incorretos', 'Estão INCORRETOS os itens'), ('correto_nos', 'Está CORRETO o que se afirma nos itens'), ('incorreto_nos', 'Está INCORRETO o que se afirma nos itens')], help_text='Tipo de instrução para questões de afirmações', max_length=20, null=True, verbose_name='Tipo de Instrução'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('certo_errado', 'Certo/Errado'), ('afirmacoes', 'Afirmações')], default='multipla_escolha', max_length=20, verbose_name='Tipo'),
        ),
    ]
