# Generated by Django 4.2.7 on 2025-09-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_questao_afirmacoes_questao_instrucao_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='instrucao_vf',
            field=models.CharField(blank=True, help_text="Instrução específica para questões V/F (ex: 'a sequência correta obtida no sentido de cima para baixo')", max_length=200, null=True, verbose_name='Instrução V/F'),
        ),
        migrations.AddField(
            model_name='questao',
            name='sequencia_resposta',
            field=models.CharField(blank=True, help_text="Sequência de V/F para questões do tipo 'Verdadeiro ou Falso' (ex: V-V-F-V)", max_length=10, null=True, verbose_name='Sequência V/F'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('certo_errado', 'Certo/Errado'), ('afirmacoes', 'Afirmações'), ('afirmacoes_variadas', 'Afirmações com Alternativas Variadas'), ('verdadeiro_falso', 'Verdadeiro ou Falso com Sequência')], default='multipla_escolha', max_length=20, verbose_name='Tipo'),
        ),
    ]
